name: Smart Mail Sender

on:
  schedule:
    # Runs every day at 2:30 a.m. UTC (8:00 a.m. IST)
    - cron: '30 2 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Run the Python script
      - name: Run Python Script
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python gmailsender.py
